### ISSUE TITLE
go test failed with TestBytesReader

### ISSUE THREAD

**Issue by LukeEuler** [Dreamacro/protobytes#3]
version: last commit 6500a9f4f15818b9854dec9e8f14584d61062555

golang version: go version go1.20.8 darwin/arm64

Description:
go test -timeout 30s -run TestBytesReader github.com/Dreamacro/protobytes

--- FAIL: TestBytesReader (0.00s)
    bytes_test.go:19:
        	Error Trace:	/Users/luke/git/go/protobytes/bytes_test.go:19
        	Error:      	Not equal:
        	            	expected: 0
        	            	actual  : 8
        	Test:       	TestBytesReader
FAIL
FAIL	github.com/Dreamacro/protobytes	0.491s
FAIL

**Comment by Dreamacro** [comment]
It was testing for the expected value error, thanks for the report, it's fixed.
